# Generated by Django 3.2.16 on 2023-03-30 20:32

import catalog.validator
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('name', models.CharField(default='', max_length=150, unique=True, verbose_name='название')),
                ('slug', models.SlugField(default='', max_length=200, unique=True, verbose_name='слаг')),
                ('weight', models.BigIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(32767), django.core.validators.MinValueValidator(0)], verbose_name='вес')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'default_related_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('name', models.CharField(default='', max_length=150, unique=True, verbose_name='название')),
                ('text', models.TextField(default='', validators=[catalog.validator.Validator('роскошно', 'превосходно')], verbose_name='Описание')),
                ('category', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='catalog.category', verbose_name='категории')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'default_related_name': 'item',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('name', models.CharField(default='', max_length=150, unique=True, verbose_name='название')),
                ('slug', models.SlugField(default='', max_length=200, unique=True, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'default_related_name': 'tag',
            },
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='uploads', verbose_name='фото')),
                ('item', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
            ],
            options={
                'verbose_name': 'Логотип',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='item', to='catalog.Tag', verbose_name='тег'),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='uploads', verbose_name='фото')),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
            ],
            options={
                'verbose_name': 'Фотография галереи',
                'verbose_name_plural': 'Галерея',
            },
        ),
    ]
