# Generated by Django 3.2.16 on 2023-02-25 09:36

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Название')),
                ('slug', models.CharField(default='', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), 'Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.', 'invalid'), django.core.validators.MaxLengthValidator(200)], verbose_name='Ссылка')),
                ('weight', models.BigIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(32767), django.core.validators.MinValueValidator(0)], verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Название')),
                ('slug', models.CharField(default='', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), 'Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.', 'invalid'), django.core.validators.MaxLengthValidator(200)], verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Название')),
                ('text', models.TextField(default='', validators=[catalog.models.text_validator], verbose_name='Описание')),
                ('category', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalog.category', verbose_name='категории')),
                ('tags', models.ManyToManyField(related_name='items', to='catalog.Tag', verbose_name='тег')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
