# Generated by Django 3.2.16 on 2023-03-01 13:28

import re

import django.core.validators
from django.db import migrations
from django.db import models
import django.db.models.deletion

import catalog.validator


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="публикация"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        default="",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[-\\w]+\\Z"),
                                "Enter a valid “slug” consisting of Unicode"
                                "letters, numbers, underscores, or hyphens.",
                                "invalid",
                            ),
                            django.core.validators.MaxLengthValidator(200),
                        ],
                        verbose_name="слаг",
                    ),
                ),
                (
                    "weight",
                    models.BigIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MaxValueValidator(32767),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="вес",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="публикация"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        default="",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[-\\w]+\\Z"),
                                "Enter a valid “slug” consisting of Unicode"
                                "letters, numbers, underscores, or hyphens.",
                                "invalid",
                            ),
                            django.core.validators.MaxLengthValidator(200),
                        ],
                        verbose_name="слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="публикация"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        default="",
                        validators=[
                            catalog.validator.Validator(
                                "роскошно", "классно", "замечательно"
                            )
                        ],
                        verbose_name="Описание",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="catalog.category",
                        verbose_name="категории",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="tag",
                        to="catalog.Tag",
                        verbose_name="тег",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
