# Generated by Django 3.2.16 on 2023-03-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, verbose_name='показывается на главной'),
        ),
    ]
