# Generated by Django 3.2.16 on 2023-03-22 13:28

import re

import django.core.validators
from django.db import migrations
from django.db import models
import django.db.models.deletion

import catalog.validator


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(
                default="",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-\\w]+\\Z"),
                        "Enter a valid “slug” consisting of Unicode letters, "
                        "numbers, underscores, or hyphens.",
                        "invalid",
                    ),
                    django.core.validators.MaxLengthValidator(200),
                ],
                verbose_name="слаг",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                default="",
                validators=[
                    catalog.validator.Validator(
                        "роскошно", "классно", "замечательно", "превосходно"
                    )
                ],
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.CharField(
                default="",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-\\w]+\\Z"),
                        "Enter a valid “slug” consisting of Unicode letters, "
                        "numbers, underscores, or hyphens.",
                        "invalid",
                    ),
                    django.core.validators.MaxLengthValidator(200),
                ],
                verbose_name="слаг",
            ),
        ),
        migrations.CreateModel(
            name="MainImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload",
                    models.ImageField(
                        upload_to="uploads", verbose_name="фото"
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mainimage",
                        to="catalog.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Логотип",
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload",
                    models.ImageField(
                        upload_to="uploads", verbose_name="фото"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galleryimage",
                        to="catalog.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография галереи",
                "verbose_name_plural": "Галерея",
            },
        ),
    ]
