# Generated by Django 3.2.16 on 2023-02-22 16:46

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogcategory",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="catalogtag",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
