# Generated by Django 3.2.16 on 2023-02-22 16:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_auto_20230222_1946"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogcategory",
            name="name",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="catalogcategory",
            name="slug",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="catalogcategory",
            name="weight",
            field=models.BigIntegerField(default="100"),
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="name",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="text",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="catalogtag",
            name="name",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="catalogtag",
            name="slug",
            field=models.TextField(default=""),
        ),
    ]
