# Generated by Django 3.2.16 on 2023-03-30 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20230322_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'default_related_name': 'category', 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'default_related_name': 'item', 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tag', 'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='catalog.category', verbose_name='категории'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='item', to='catalog.Tag', verbose_name='тег'),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='item',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.item'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True, verbose_name='слаг'),
        ),
    ]
