# Generated by Django 3.2.16 on 2023-02-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='categories',
        ),
    ]
