# Generated by Django 3.2.16 on 2023-02-22 18:28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_catalogcategory_weight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalogcategory",
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="catalogitem",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="catalogtag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.AlterField(
            model_name="catalogcategory",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Публикация"),
        ),
        migrations.AlterField(
            model_name="catalogcategory",
            name="name",
            field=models.CharField(
                default="", max_length=150, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="catalogcategory",
            name="slug",
            field=models.CharField(
                default="", max_length=150, verbose_name="Ссылка"
            ),
        ),
        migrations.AlterField(
            model_name="catalogcategory",
            name="weight",
            field=models.BigIntegerField(default=100, verbose_name="Вес"),
        ),
        migrations.AlterField(
            model_name="catalogitem",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Публикация"),
        ),
        migrations.AlterField(
            model_name="catalogitem",
            name="name",
            field=models.CharField(
                default="", max_length=150, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="catalogitem",
            name="text",
            field=models.TextField(default="", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="catalogtag",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Публикация"),
        ),
        migrations.AlterField(
            model_name="catalogtag",
            name="name",
            field=models.CharField(
                default="", max_length=150, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="catalogtag",
            name="slug",
            field=models.CharField(
                default="", max_length=150, verbose_name="Ссылка"
            ),
        ),
    ]
