# Generated by Django 3.2.16 on 2023-02-22 20:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_auto_20230222_2156"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogitem",
            name="tags",
            field=models.ManyToManyField(
                related_name="items",
                to="catalog.CatalogTag",
                verbose_name="тег",
            ),
        ),
    ]
