# Generated by Django 3.2.16 on 2023-02-24 17:08

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_catalogitem_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogitem",
            name="category",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_categories",
                to="catalog.catalogcategory",
                verbose_name="категории",
            ),
        ),
    ]
