# Generated by Django 3.2.16 on 2023-02-24 21:41

import catalog.models

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_catalogitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogcategory",
            name="weight",
            field=models.BigIntegerField(
                default=100,
                validators=[catalog.models.weight_validator],
                verbose_name="Вес",
            ),
        ),
    ]
